name: myfatoorah_flutter
version: 2.1.2 # Don't forget to update this number inside the "getPluginVersion" method in "SourceInfo.dart" file and in README file and CHANGELOG file
description:
  This plugin simplify the MyFatoorah payment platforms integration with your app, that works smoothly
  and provide you a simple way to embed our payment functions within your app.
documentation: https://myfatoorah.readme.io/docs/flutter
homepage: https://dev.azure.com/myfatoorahsc/_git/MF-SDK-Cross-Platforms-Demos

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.1
  device_info: ^2.0.0
  webview_flutter: ^2.0.12

  # back_button_interceptor: ^5.0.1
  # flutter_webview_plugin: ^0.4.0 #Support Apple pay

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  plugin:
    platforms:
      android:
        package: com.myfatoorah.flutter
        pluginClass: MyfatoorahFlutterPlugin
      ios:
        pluginClass: MyfatoorahFlutterPlugin
